name: Docker CI/CD Pipeline

on:
  push:
    branches:
      - main  # A pipeline minden main branch-re történő push esetén fut

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{zsolti9017}}
          password: ${{Dvsc1902!}}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Get current date for tag
        id: date
        run: echo "DATE=$(date +'%Y%m%d%H%M')" >> $GITHUB_OUTPUT

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/hello-devops-app:latest
            ${{ secrets.DOCKER_USERNAME }}/hello-devops-app:${{ steps.date.outputs.DATE }}